spring:
  application:
    name: customer-domain-people
    version: 1.0.0
    description: Customer Domain People Layer Application
    team:
      name: Catalis Development
      email: dev@catalis.com

  threads:
    virtual:
      enabled: true


firefly:
  saga.performance.enabled: true
  events:
    adapter: kafka  # or 'auto' for auto-detection
    kafka:
      bootstrap-servers: localhost:9092
      retries: 3
      batch-size: 16384
      acks: all

  stepevents:
    enabled: true

server:
  port: 8082
  shutdown: graceful

# Clients basePath
api-configuration:
  common-platform.customer-mgmt:
    base-path: http://localhost:8081

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tagsSorter: alpha
    operationsSorter: method
    docExpansion: none
    filter: true
  packages-to-scan: com.firefly.domain.people.web.controller
  paths-to-match: /api/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
    redis:
      enabled: false

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: INFO
    com.firefly: DEBUG
    org.springframework.r2dbc: DEBUG
    org.flywaydb: DEBUG

---
spring:
  config:
    activate:
      on-profile: testing

logging:
  level:
    root: INFO
    com.firefly: DEBUG
    org.springframework.r2dbc: INFO

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

---
spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    root: WARN
    com.firefly: INFO
    org.springframework: WARN

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false